import React from "react";
import {
  Box,
  HStack,
  Heading,
  Stack,
  Tag,
  TagLabel,
  VStack,
} from "@chakra-ui/react";

const Skills = () => {
  return (
    <>
      <Box
        display="flex"
        justifyContent="center"
        alignItems="center"
        textColor="white"
        marginTop={["30px", "40px"]}
      >
        <Heading size="3xl" fontWeight={"bold"}>
          Skills
        </Heading>
      </Box>
      <Box
        display="flex"
        justifyContent="center"
        alignItems="center"
        height="55vh"
        textColor="white"
      >
        <Stack direction={["column", "column", "column"]} spacing={[4, 8, 8]}>
          <Stack
            display="flex"
            justifyContent="center"
            alignItems="center"
            direction={"row"}
            spacing={5}
          >
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>C</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>C++</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Python</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Java</TagLabel>
            </Tag>
          </Stack>
          <Stack
            display="flex"
            justifyContent="center"
            alignItems="center"
            direction={"row"}
            spacing={5}
          >
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>HTML</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>CSS</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>JavaScript</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Bootstrap</TagLabel>
            </Tag>
          </Stack>
          <Stack
            display="flex"
            justifyContent="center"
            alignItems="center"
            direction={"row"}
            spacing={5}
          >
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>React</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Chakra UI</TagLabel>
            </Tag>
          </Stack>
          <Stack
            display="flex"
            justifyContent="center"
            alignItems="center"
            direction={"row"}
            spacing={5}
          >
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Nodejs</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>MongoDB</TagLabel>
            </Tag>
          </Stack>
          <Stack
            display="flex"
            justifyContent="center"
            alignItems="center"
            direction={"row"}
            spacing={5}
          >
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Scikit-learn</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>Numpy</TagLabel>
            </Tag>
            <Tag
              size="lg"
              borderRadius="full"
              variant="solid"
              colorScheme="green"
            >
              <TagLabel>PyTorch</TagLabel>
            </Tag>
          </Stack>
        </Stack>
      </Box>
    </>
  );
};

export default Skills;
